sudo: false
language: java

jdk: openjdk15

cache:
  directories:
    - $HOME/.m2

install: /bin/true

script:
  - mvn package -Dmaven.javadoc.skip=true -V -B

after_success:
  - bash <(curl -s https://codecov.io/bash)